security:

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    providers:
            in_memory:
                memory:
                    users:
                        user:  { password: user, roles: 'ROLE_USER' }
                        admin: { password: admin, roles: 'ROLE_ADMIN' }

    firewalls:
            secured_area:
                pattern:   ^/
                anonymous: ~
                http_basic:
                    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

